
  <div class="container">
    <div class="container-form"><form style="display: flex; flex-direction: column; width: 30%; margin: 0 auto;" method="POST" action="/usuario/<?php echo $this->view->usuario[0]->getId(); ?>/update"><h3> Edição de Usuario </h3>  <div class="form-group"><label>Id</label>
        <input type="text" name="id" class="form-control" value="<?php echo $this->view->usuario[0]->getId(); ?>" required>  </div>  <div class="form-group"><label>Nome</label>
        <input type="text" name="nome" class="form-control" value="<?php echo $this->view->usuario[0]->getNome(); ?>" required>  </div>  <div class="form-group"><label>Login</label>
        <input type="text" name="login" class="form-control" value="<?php echo $this->view->usuario[0]->getLogin(); ?>" required>  </div>  <div class="form-group"><label>Senha</label>
        <input type="text" name="senha" class="form-control" value="<?php echo $this->view->usuario[0]->getSenha(); ?>" required>  </div><button type="submit" class="btn btn-success">Salvar</button>
</form></div>
  </div>