<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Auto CRUD</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(Página atual)</span></a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Listagem
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="nav-link" href="/usuario">Usuario<span class="sr-only">(Página atual)</span></a><a class="nav-link" href="/produto">Produto<span class="sr-only">(Página atual)</span></a><a class="nav-link" href="/fornecedor">Fornecedor<span class="sr-only">(Página atual)</span></a><a class="nav-link" href="/cliente">Cliente<span class="sr-only">(Página atual)</span></a>        
      </div>
      </li>
        </ul>
      </div>
    </nav>