
  <div class="container">
    <div class="container-form"><form style="display: flex; flex-direction: column; width: 30%; margin: 0 auto;" method="POST" action="/produto/<?php echo $this->view->produto[0]->getId(); ?>/update"><h3> Edição de Produto </h3>  <div class="form-group"><label>Id</label>
        <input type="text" name="id" class="form-control" value="<?php echo $this->view->produto[0]->getId(); ?>" required>  </div>  <div class="form-group"><label>Descricao</label>
        <input type="text" name="descricao" class="form-control" value="<?php echo $this->view->produto[0]->getDescricao(); ?>" required>  </div>  <div class="form-group"><label>Ncm</label>
        <input type="text" name="ncm" class="form-control" value="<?php echo $this->view->produto[0]->getNcm(); ?>" required>  </div>  <div class="form-group"><label>Estoque</label>
        <input type="text" name="estoque" class="form-control" value="<?php echo $this->view->produto[0]->getEstoque(); ?>" required>  </div><button type="submit" class="btn btn-success">Salvar</button>
</form></div>
  </div>