
                  <?php require_once __DIR__ . "\..\header.phtml" ?>

                    
                    <div style="margin-top: 20px" align="right" class="container">
                    <div  class="row">
                      <div class="col-md-12">
                      <a href="cliente/cadastrar" class="btn btn-success">
                      <span class="fa fa-plus" aria-hidden="true"></span>
                      Incluir
                      </a>
                      </div>
                    </div>
                      <table style="margin-top: 10px" class="table table-striped tabela-consulta">
                          <thead>
                              <tr align="center">
                                  <th>Id</th><th>Nome</th><th>Cpf</th><th>Rg</th><th> Ações </th>
                              </tr>
                          </thead>
                          <tbody>
                          
                  <div class="table-responsive">

                              <?php foreach ($this->view->cliente as $cliente): ?>
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirma exclusão?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body">
                                        Tem certeza que deseja deletar?
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">NÃO</button>
                                        <a href="cliente/<?php echo $cliente->getId(); ?>/delete"><button type="button" class="btn btn-danger">SIM</button></a>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <tr>
                                  <td align="center" style="vertical-align: middle;"><?php echo $cliente->getid(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $cliente->getnome(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $cliente->getcpf(); ?> </td><td align="center" style="vertical-align: middle;"><?php echo $cliente->getrg(); ?> </td>
                                  <td style="width: 100px" align="center" class="actions">
                                  <div class="justify-content-center d-flex flex-row">
                                      <div style="margin-bottom: 5px;">
                                        <a class="mr-3" href="cliente/<?php echo $cliente->getId(); ?>/findById" id="botao-alterar" class=""><i style="color: #c1c1c1" class='fas fa-pencil-alt' style='font-size:28px'></i></a>
                                      </div>
                                      <div>
                                        <a data-toggle="modal" data-target="#exampleModal"  id="botao-excluir" class=""><i style="color: #c1c1c1" class='fas fa-trash' style='font-size:28px'></i></a>
                                      </div>
                                  </div>
                                  </td>
                                </tr>
                              <?php endforeach; ?>
                          </tbody>
                      </table>
                  </div>
                  </div>